### ISSUE TITLE
youtube plugin not updating as expected.

### ISSUE THREAD

**Issue by jpdacostaza** [PhasecoreX/docker-red-discordbot#101]
While running managed audio by default it downloads the plugin : youtube-plugin-1.7.2.jar <-- Which is no longer working

lavalink:
  plugins:
  - dependency: dev.lavalink.youtube:youtube-plugin:1.7.2
    repository: https://maven.lavalink.dev/releases

kindly update configuration to pull latest https://maven.lavalink.dev/#/releases/dev/lavalink/youtube/youtube-plugin/1.8.3
to /data/cogs/Audio/plugins as the new plugin :youtube-plugin-1.8.3.jar <-- which is working. 

if plugin is replaced and unload then reload audio it works fine I have tried to set tokens and api and does not seem to be working with 1.7.2. at all

I have tried to replace these files manually but upon container restart it reverts the Audio directory and configs to the repo.

**Comment by PhasecoreX** [comment]
This container image doesn't actually do the lavalink downloading/management, that's entirely done by the Redbot audio cog. All this container does is provide an environment for Redbot to run in.

If you want to set the audio cog to use unmanaged lavalink and manually download/run lavalink yourself, you can do that. Otherwise, the audio cog will always download the version of lavalink for the current version of Redbot.

If you don't want to do that manual stuff, you just have to wait until Redbot has a new release, which is hopefully soon.

**Comment by jpdacostaza** [comment]
another thing is how if i set unmanged can I create a service

**Comment by PhasecoreX** [comment]
I'm not 100% sure since I don't run lavalink separate, but as far as I know, you'd have to either run it in a separate container or on the host. If on the host, you'd have to run the Redbot container in host networking mode. If you run it in a container, you'd have to make sure both the Lavalink container and Redbot container are in the same docker network. You could probably also run it directly inside the Redbot container by interactively entering the container, but that's a messy manual process.

**Comment by LZeugirdor** [comment]
> I'm not 100% sure since I don't run lavalink separate, but as far as I know, you'd have to either run it in a separate container or on the host. If on the host, you'd have to run the Redbot container in host networking mode. If you run it in a container, you'd have to make sure both the Lavalink container and Redbot container are in the same docker network. You could probably also run it directly inside the Redbot container by interactively entering the container, but that's a messy manual process.

Can also just set the network to the container while setting the cog to unmanaged, at least I think that should work and would probably require less effort because it'll be on localhost in the container.
