### ISSUE TITLE
lavalink not working (i think)

### ISSUE THREAD

**Issue by Obstidian** [PhasecoreX/docker-red-discordbot#103]
**Describe the bug**
discord bot not working (i think it is because of lavalink)

**Run command**
```
default command in unraid
```

**Environment info:**
unraid

**Additional context**
any eta on when this will be fixed? Sorry, I am not too much familiar with whole linux at the moment. So it could be something wrong on my side.

**Comment by PhasecoreX** [comment]
I don't actually have Unraid, and didn't make the image(?) that's present on there. Do you have any logs or anything?

**Comment by Roxedus** [comment]
Post your run command. it should be visible once you enable advanced mode on the edit container screen, and either make a change, or choose save.

**Comment by Obstidian** [comment]
this, right?

![image](https://github.com/user-attachments/assets/dbebeefb-6fc6-4c84-8d4d-1a8e9d102e1d)
![image](https://github.com/user-attachments/assets/2aba5684-da95-4abf-9609-33b90fad89ad)

**Comment by PhasecoreX** [comment]
So we still don't know what "not working" means. What is it doing and what are you expecting it to do?

I still see `/config` being used in these Unraid setups, not sure why since the container stores everything in `/data`... Oh also it looks like that is being set as an environment variable instead of a volume. So that could be something not working. Again I don't have Unraid so I'm just guessing here.

**Comment by Roxedus** [comment]
My template uses /data.
@TeddyTux should fix his template, it is broken ottb.

**Comment by Obstidian** [comment]
oh okay, so Im on wrong repo? anyway the thing not doing what it should is lavalink, more exactly playing urls from youtube. It looks like ytb changed API again so it is broken. From what I understand, the official repo is already working. So I thought since your name came up in the repo I am using, I will need to ask you when it will be updated.

**Comment by PhasecoreX** [comment]
Yeah Lavalink (the part that plays YouTube) is not working in the current version of Redbot. There are ways to manually update it, but that has nothing to do with this container repo. My container is just an environment for Redbot to run in, it doesn't actually do anything else besides download and run Redbot. Redbot is the one managing its own cogs and Lavalink.

If you want to manually update Lavalink, you can join Redbots official support discord and learn more there. Otherwise you just have to wait until they release a new version (should be soon?). At that point, simply restarting the bot will update.
