### ISSUE TITLE
Can't Perform Initial Setup

### ISSUE THREAD

**Issue by Deus-Rex** [PhasecoreX/docker-red-discordbot#2]
I am trying to follow the guide, but unfortunately am tripping over the first step. Running the command  `docker run -it --rm -v ~/discbot:/data -e PUID=99 -PGID=100 phasecorex/red-discordbot` pulls the image and installs the dependencies, but fails near the end with the response:

> You need to configure the bot instance using `redbot-setup` prior to running the bot.

I expect that this setup was supposed to start for me, but for some reason failed.  The other lines returned in the terminal are related to pip packages already being satisfied.

My system runs unRAID, so it could be funny business with how it deals with Docker. I'm not fully clued up on this yet to tell.

Cheers.

**Comment by PhasecoreX** [comment]
Congrats! You're the first person to try and use a sub-1000 user ID! Turns out redbot will look in a different location for settings if the user ID is less than 1000 (and greater than 0):

https://github.com/Cog-Creators/Red-DiscordBot/blob/c7608aeb1728c1f06d46b2bc441e4c78dd5e157d/redbot/core/data_manager.py#L38

Of course, I tested with the ID 0 and 1000, so I missed this case. I will get a fix out for this before the end of the day!

**Comment by Deus-Rex** [comment]
Hah, thanks for the quick response. I'm not fully aware of why unRAID suggests that user and group, but it is used with everything, and it doesn't seem like it would be a good idea to use a different user. I don't know enough to say that with certainty, but it is the impression that I have gotten.

If a fix is reasonable, I will wait for that before I give using an alternative user a shot. I'll ask for advice somewhere with unRAID support whether it is an okay idea.

**Comment by PhasecoreX** [comment]
Yes, the fix is very easy. I have tested the fix, built, and pushed the new docker image to the hub. Pull the new image and give it a try!

**Comment by Deus-Rex** [comment]
It has been a few weeks now, and I've only now managed to make time to try it out. It worked perfect, thank you. I appreciate you taking the time to help.
