### ISSUE TITLE
Requirement for Fox-V3 qrinvite: MyQR

### ISSUE THREAD

**Issue by Griefed** [PhasecoreX/docker-red-discordbot#22]
**Is your feature request related to a problem? Please describe.**
I've added the Fox-V3 repo and wanted to install the qrinvite cog. It failed to install the requirement MyQR
```
Failed to install requirements: MyQR
```

**Describe the solution you'd like**
If possible, add required dependencies so qrinvite can be installed

**Describe alternatives you've considered**
Not using qrinvite. :D

**Additional context**
Here's the log of the bot, if it helps: https://pastebin.com/unJWvFum
Not sure if the whole thing corresponds to qrinvite, I couldn't discern the entries.

**Comment by PhasecoreX** [comment]
Since I am able to install it with no changes (amd64 architecture, docker full tag). I'm going to assume that it's an issue with the fact that you're using a raspberry pi (or some other arm32 device). Usually numpy is installed with the help of a python wheel (a precompiled package), but since there isn't one for python 3.8 arm, it needs to compile manually.

Of note, I see this line in your logs:
```
 gcc: fatal error: Killed signal terminated program cc1
```

Based on a bit of searching, that might be caused by running out of memory during the compile. Since raspberry pi's usually have 1GB of RAM, that might be what's breaking it.

My suggestions off the top of my head are:
1. Stop every other docker container and retry the cog install.
2. Restart the whole raspberry pi (or whatever you have), start only the bot container, and retry the cog install.
3. (Very advanced) attach a USB drive to the pi and designate it as a cache partition, install the cog, then somehow remove the cache partition (so you don't kill your USB drive with several writes) (I have never tried this)

Maybe you can repeat step 2 a couple of times, in case it ends up installing numpy but then fails on the second package it needs to install. Once they are all installed you shouldn't ever need to reinstall them as far as I know.

**Comment by Griefed** [comment]
Thank you very much for your input. It didn't even occur to me that it may be due to the ARM architecture and the fact that my Pi has insufficient amounts of RAM.
I'll give it a shot. :)
