### ISSUE TITLE
Pillow / Python Imaging Library

### ISSUE THREAD

**Issue by TomasJAnderson** [PhasecoreX/docker-red-discordbot#23]
Hello,

Would it be possible to add the pillow library ? 
Or a quick explenation on how to load it manually ?

Thank you in advance.

**Comment by PhasecoreX** [comment]
It should just install automatically when you go to install a cog that requires it, at least that's what has worked for me. Are you running into an error message of some sort?

If for some reason that doesn't work, you can try using `[p]pipinstall` to manually install it. Otherwise it's a bit more involved manually activating the venv and installing your dependencies manually (which I've never had to do)

**Comment by TomasJAnderson** [comment]
[p]pipinstall did the trick ! Thank you for you support.
