### ISSUE TITLE
Add support for red-dashboard

### ISSUE THREAD

**Issue by stephanrenggli** [PhasecoreX/docker-red-discordbot#40]
**Is your feature request related to a problem? Please describe.**
As RPC/ZMQ of red-bot will be limited to localhost only (security limitation), it won't be possible to host the red-dashboard webserver in another container. If one would like to use red-dashboard it would have to run in the same container as red-bot itself.

**Describe the solution you'd like**
Support for red-dashboard in this docker container.

From what I can tell the following modifications would have to be made:
1.  Installation of up to three pip packages:
    - setuptools
    - wheel
    - Red-Dashboard

    Installation instructions: https://red-dashboard.readthedocs.io/en/latest/mac_linux_installation.html#using-venv

2. The `--rpc` (`--rpc <port>`) flag would have to be added to the bot start command (https://red-dashboard.readthedocs.io/en/latest/running_webserver_one_bot.html). Possibly with an environment variable to customize the rpc port.

3. The dashboard webserver would have to be started in addition to the bot itself with the command `reddash` (`reddash --port <webserver_port> --rpc-port <rpc_port>`) (https://red-dashboard.readthedocs.io/en/latest/running_webserver_one_bot.html#running-the-webserver). Possibly with environment variables to customize rpc and webserver ports.

Maybe this could be an additional version (like noaudio, audio, full and now *dashboard*).

**Describe alternatives you've considered**
- It is possible to run red-dashboard with this docker image by installing everything manually after the container has started. Obviously this does not make a lot of sense and isn't very user friendly at the moment.

- Another option would be to just create a custom image which installs everything from the start. I have tried this and it worked fine.

**Additional context**
I'm not sure if it makes sense to add this now as the dashboard is still in alpha and is not suggested for production use. It would be nice to have support for this eventually though.

**Comment by PhasecoreX** [comment]
I've thought about this for a while now, but no, I don't think I want to add the red dashboard in this image.

Couple of reasons for that, the main one being that it's not fun managing multiple processes in one container, as it goes against the container philosophy of one (main) process per container. Second, it seems like scope creep. For now it's just the dashboard, but what if in the future there are other projects that need to run alongside the bot in order to use it's RPC? I don't want to have to pick and choose and manage all of those combinations. Lastly, from an end user experience, it wouldn't be too great if you needed to restart/update your bot and it took down the entire dashboard website with it.

A third alternative to your above two is that you can run this container in host network mode, and then run the dashboard on the host. Since they are both on the host, localhost RPC works fine. We have one person on my support Discord server that said it was working for them that way.

Hopefully in the future they allow the bot to listen to RPC on more than just localhost (with maybe a big warning, password enforcement, and maybe only allow certain IP ranges), so that it could talk with another container. That would be ideal. Then I could make a container for the dashboard perhaps.

I am leaving this open for now so that I remember to update the readme to explain how using host networking mode can allow for the dashboard to work.

**Comment by djfaizp** [comment]
Now cog is available but i don't know how to fix it

**Comment by PhasecoreX** [comment]
Please open a new issue with more information about the problem you are facing. This is an issue from 3 years ago and not about a cog.
