### ISSUE TITLE
External LavaLink instance because of a bug

### ISSUE THREAD

**Issue by tctfox** [PhasecoreX/docker-red-discordbot#54]
The bot works fine as it is. But a general problem with normal redbot and yours seem to  be that after a couple of days the error "Connection to Lavalink has been lost." appears and only a bot restart can fix it.
Another fix is running lavalink externally and setting redbot up to work like that. This doesn't work wtih your docker image tho, I am sure connectivity problem outside of the docker.
Is there any way to make this work? Help would be appreciated

**Comment by PhasecoreX** [comment]
If you're running the lavalink server externally, you would have to run the container in host networking mode so that it could see the server on your localhost. If lavalink is in a different container, you would have to make sure both containers are in the same docker network.

If running it internally doesn't work on regular non-docker install, then that probably isn't an issue with this image.

**Comment by joshuakohut77** [comment]
@tctfox have you had any luck with getting this to work? I want to try an external link as pretty much every day I have the "Connection to Lavalink has been lost" error that can only be fixed by a bot restart. I will probably try to get this working in the next day or two but wanted to see if you had any thoughts on the process

**Comment by joshuakohut77** [comment]
I wanted to follow up and say I was able to get this docker image working with an external lavalink docker image. I both containers in the same docker network and changed the lavalink wsport away from the default so there was no confusion. After using `.llsetup` command and connecting it to the external service it worked great. Time will tell if I have the same "Connection to Lavalink has been lost" error.

**Comment by PhasecoreX** [comment]
Nice! Good to know that external Lavalink works fine with the container.

**Comment by joshuakohut77** [comment]
I don't want to reopen this but just wanted to let @tctfox and anyone else to know that I've had an external Lavalink setup and it's ran for 3 days now without getting the "Connection to Lavalink has been lost." error which I used to get every night. I agree there's something bugged wit the internal service. This is a work around but solved the issue of needing to restart the container every day.
