### ISSUE TITLE
Request for python 3.11 version

### ISSUE THREAD

**Issue by herrnn** [PhasecoreX/docker-red-discordbot#59]
Its seems like some of the cogs are developed for python 3.11 but its seems like there's only version 3.9 available

Would it be possible to have a branch of python 3.11 along side 3.9?

**Comment by Luc1412** [comment]
@PhasecoreX  Any news regarding it? Red 3.5 is now already in a good state and supports 3.10 and 3.11. Also many 3rd party cogs got a 3.5 branch

Some like to upgrade to 3.5 now, as discord will shutdown Redbot 3.4 with discord.py 1.3.7 that uses a deprecated api version.

**Comment by PhasecoreX** [comment]
I'm basing my install on the instructions here: https://docs.discord.red/en/stable/install_guides/debian-11.html Once that says to use 3.11 I will switch over to it. Also since the image defaults to latest release of redbot, that's still 3.4, which is still python 3.9.

I've asked the redbot developers if it is safe to use python 3.11 with the latest redbot. If it is, I will switch over to it.

**Comment by Luc1412** [comment]
This could be solved with a 3.5 branch (like many cog repos already got). Alternatively an extra tag where you explicitly select 3.10/3.11 could be also possible. 

Unfortunately Red's communication is kinda awful, as they doesn't provide a clear timeline when 3.5 will be release (which should be necessary due to the api version shutdown). Starting Red 3.5 migration now is mandatory otherwise it might be too late and you don't get it in time.

**Comment by PhasecoreX** [comment]
Python 3.11 version will be available once RedBot 3.5 comes out, which is hopefully soon. The update will be automatic, just an image pull and update.
