### ISSUE TITLE
Can you use MongoDB with this?

### ISSUE THREAD

**Issue by Deanosim** [PhasecoreX/docker-red-discordbot#6]
Like the title says, It's probably simple, but I don't know if your image support it yet.

**Comment by PhasecoreX** [comment]
At the moment, no. It is hard coded to using JSON as its storage type, for ease of setup and usage: [config.json](https://github.com/PhasecoreX/docker-red-discordbot/blob/febc95c63a29c64f0e2b8fb9202b064bfb7f1b74/root/config/.config/Red-DiscordBot/config.json). The updater is also set up to only install Red-DiscordBot, not the additional MongoDB stuff.

However, it should be decently easy to add this support. Simple environment variables being set could dictate that we download the MongoDB extras, and then set the connection parameters. I will look into this.

**Comment by Deanosim** [comment]
Oh awesome, Yeah I was just wondering because I want to setup multiple backend instances for the same bot, and currently I'm not sure how to go about doing it, Although i think I need Sharding.

**Comment by PhasecoreX** [comment]
I think sharding comes into play once your bot joins over 2500 different servers, at which point a) I am honored you're using my image, and b) Red-DiscordBot should automatically take care of doing the actual sharding, regardless of backend storage, so you and I don't need to do anything about it. One bot instance, one storage system, any number of servers, all automatic.

On that note, MongoDB support should now be working! Simply set the following environment variables to get started:
- `STORAGE_TYPE`: Can either be `mongodb` or `mongodb+srv` (by default this is `json`)
- `MONGODB_HOST`
- `MONGODB_PORT`: Defaults to 27017
- `MONGODB_USERNAME`
- `MONGODB_PASSWORD`
- `MONGODB_DB_NAME`
Check the readme for more info. Let me know if something isn't working correctly!

**Comment by Ryonez** [comment]
@PhasecoreX 
What is the difference between `mongodb` or `mongodb+srv`?

**Comment by PhasecoreX** [comment]
I actually don't even know, I was just exposing all the options of the underlying Red-DiscordBot. Here's what I found on the matter:

In order to leverage the DNS seedlist, use a connection string prefix of mongodb+srv: rather than the standard mongodb:. The +srv indicates to the client that the hostname that follows corresponds to a DNS SRV record. The driver or mongo shell will then query the DNS for the record to determine which hosts are running the mongod instances.

So I guess if you have a SRV record set up at your DNS provider to point at your MongoDB server, you can use that. But I assume for the vast majority of users, they would just use the mongodb option and point directly at their MongoDB server. If it's docker, it would be the MongoDB container name.

Hopefully that helps!

**Comment by Ryonez** [comment]
It does indeed, thank you.
