### ISSUE TITLE
Autorestart

### ISSUE THREAD

**Issue by daNutzzzzz** [PhasecoreX/docker-red-discordbot#63]
Hi,

Does this container contain a way for the bot to auto restart upon it being disconnected from discord? like: https://docs.discord.red/en/stable/autostart_systemd.html

**Comment by PhasecoreX** [comment]
I think the bot already auto reconnects to Discord when it loses connectivity. If you're talking about the container itself crashing (unlikely) or the bot stopping, you can start the container with a restart policy so that the container will automatically restart.

See https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by daNutzzzzz** [comment]
Hi, no not the container, the bot doesn't reconnect if it losses access to discord from say a blip on the internet or something.

**Comment by PhasecoreX** [comment]
The documentation you linked to was just for (re)starting the bot if it ever stops. It has nothing to do with network disconnection. When the bot disconnects from Discord, the bot doesn't stop. Instead, it continues to run and retries connecting. If that's not the case, that's an issue with the bot or your network, not the container.

For the container, or your linked systemd documentation, they don't know if the bot is connected to the Discord servers or not. They only make sure that the bot is running. Network disconnection handling is done by the bot, not the container/systemd.

**Comment by daNutzzzzz** [comment]
ok thanks, i will monitor further

**Comment by PhasecoreX** [comment]
Closing as it has been a while. Let me know if it continues to happen, especially once RedBot 3.5 is out.
