### ISSUE TITLE
add co-owner

### ISSUE THREAD

**Issue by gilbN** [PhasecoreX/docker-red-discordbot#8]
Hi! 

I was wondering how one would add 1 og more co-creators using this docker container?

**Comment by PhasecoreX** [comment]
Until about an hour ago, I had no idea what co-owners were. I have added an environment variable called `EXTRA_ARGS` that you can use to specify extra arguments/flags to pass to the redbot process. This is how you would specify the argument required for adding a co-owner to your bot. Check the README for more information if needed.

Since the co-owner functionality is a very powerful thing, I'm just going to copy and paste the SaltBot information about it here:

---

**About the co-owner(s) feature:**
*Please be aware that this feature is for bots **hosted on servers** not on personal computers.*
To be more specific, it was designed to make it possible to give owner powers to people who would have access to the system the bot is hosted on anyway.
*Do not use this feature unless you're fine with the fact that the people you're making co-owner will be able to operate and access the system's files.*

**I have read the above and I declare that I'm not a moron, how do I do this?**
Start red.py with the `--co-owner` flag and the ID of the person you're making co-owner. You can use the flag multiple times for multiple co-owners.

**F-flags? What are those and why it's not a command instead?**
This feature is semi-hidden on purpose because it can be misused and become a huge security risk. Google command line flags for more information. If you cannot figure this out with Google, you probably shouldn't be using this feature. 

We will not be offering support past this point. The feature has been made available and you have been given fair warning and disclaimers. We are no longer liable for any security issues that may arise.

---

See? Pretty scary stuff. The build has just finished, so you can now pull the updated image and use the `EXTRA_ARGS` environment variable. Hopefully this all helps!

**Comment by gilbN** [comment]
This is great :) Thanks!
