### ISSUE TITLE
Healthcheck for livenessProbe

### ISSUE THREAD

**Issue by panromir** [PhasecoreX/docker-red-discordbot#84]
**Is your feature request related to a problem? Please describe.**
Currently I see no simple way of checking whether or not the redbot instance in the container is still running and responsive. I could check in discord itself, but this seems like a very complex workaround.

**Describe the solution you'd like**
I would like a healthcheck command or endpoint, which I can query to verify that redbot is still running and responsive.
Maybe even to return some more metrics, like if an update is available or how many cogs are loaded, etc.

**Describe alternatives you've considered**
I did consider looking into RPC.
I also checked the CLI but didn't find anything satisfactory.

**Additional context**
I want to run this as a deployment in k8s. Maybe that's overkill, but some people might find a use for this. Everything works fine so far, but the Kubernetes way would include a Readiness and Liveness Probe to ensure everything is up and running.

Thank you!

**Comment by PhasecoreX** [comment]
This was brought up in the past, not sure if it was here or in my discord support server. The issue is that I don't (think I) have a way of seeing that information. I can tell that the bot/process is running, but I can't tell if it's connected to the discord network or is otherwise responsive.

If redbot itself had a way to query it for information (directly with some command), I could add a health check to the container, or otherwise expose that info. But as far as I know it doesn't at the moment, unless there's some RPC stuff I don't know about, which is entirely possible, as I've not really looked into that.

I have a cog called Heartbeat on my PCXCogs that pings a configurable endpoint every minute. I use it with healthchecks.io to monitor if the bot is still up. I dunno if that would help?

**Comment by panromir** [comment]
Hey, thanks for your response. In that case, I will close here and maybe ask the redbot devs how to proceed or if they could add a feature like that. The healthchecks.io workaround seems like a good idea for now. 
Thanks, closing!
