### ISSUE TITLE
No full tag on docker hub

### ISSUE THREAD

**Issue by anirbanmu** [PhasecoreX/docker-red-discordbot#9]
I was trying to play with the full image described in the README. Is that one no longer supported? Thanks.

**Comment by PhasecoreX** [comment]
The build for the full tag takes a significant amount of time since ImageMagick7 needs to be built from source. Since I build these images myself (for multi-arch support), it was taking a very long time on my server to build. So, I haven't actually built or tagged them yet.

What I could do is update it so that the full tag has everything except the ImageMagick7, so the build will be much faster. Let me test this...

**Comment by anirbanmu** [comment]
It's no worries really, I can just build it myself as well from the Dockerfile.full given!

**Comment by PhasecoreX** [comment]
The given Dockerfile.full was kind of a work in progress. I've just updated it so that ImageMagick7 isn't in it anymore (and none of the build dependencies either) and that has been sent to the build server.

If you absolutely need ImageMagick7, then yeah, manually building it would be the solution. I think I needed it for the cog "notsobot" if I remember correctly. But if you want a tag that has so far covered all the other cogs I've thrown at it, then full (once it builds) should be plenty. I'll update once it builds, and if I don't, then I probably fell asleep :)

**Comment by PhasecoreX** [comment]
Okay the full tag is now back in business. Enjoy!

**Comment by anirbanmu** [comment]
Thanks! Appreciate the timeliness!
