### ISSUE TITLE
[Question] New docker image with no new redbot version

### ISSUE THREAD

**Issue by C0untZero** [PhasecoreX/docker-red-discordbot#97]
Yesterday there was a new docker image published, however there were no new commits to the main branch of this repo, nor was there a new version of the bot released.

Could you help me understand what prompted the new image version, as well as where can I find this info on my own in the future?
I can see in actions it was triggered manually, was there a new base python image (the first one in the Dockerfile) that prompted this rebuild?

Thanks!

**Comment by PhasecoreX** [comment]
Yes, I have a cron job that checks once a day if the base image this image is using has been updated. If it has, it starts the GitHub Action to rebuild and publish. That way, we keep everything up to date with whatever security updates upstream has added.

If you use my [UpdateNotify](https://github.com/PhasecoreX/PCXCogs) cog, it will check for this and let you know if an image update was caused by new commits or by upstream updates. RedBot updating will almost never cause an image update though, as they are decoupled. Each time you start the container it will try updating RedBot contained inside. That way, I don't have to remember to stay in lockstep with the RedBot developers.

**Comment by C0untZero** [comment]
Awesome, thanks for the explanation!
