### ISSUE TITLE
[BUG REPORT] All settings wiped, all cogs unloaded

### ISSUE THREAD

**Issue by 7eventy7** [PhasecoreX/docker-red-discordbot#98]
Hey there, having a really weird issue. My docker containers all automatically backup and restart once a week and this time when the bot restarted it messed up heavily. I'm not sure what else is broken but it made all the cogs I had loaded vanish, they don't even show up in unloaded anymore. The official discord does not support docker installs so you are my next best resource for figuring out what's happening. I'm seeing a few other people have had this issue before, but I haven't been able to pin-point why this happens or what can be done to update without clearing everything.

Before auto update:
![image](https://github.com/user-attachments/assets/78208019-6622-4d9b-8f89-b69fc0ef97e2)

After auto update:
![image](https://github.com/user-attachments/assets/9de8abb6-7430-4dc0-a4f4-cbbedd956ea1)

**Comment by PhasecoreX** [comment]
When your containers backed up and restarted, was the `/data` volume mounted back again? In my setup, I have my `/data` volume mounted to disk, not a named volume. Never have had an issue updating or restarting the container.

Can you provide info on how you are running your container? The docker-compose.yml or the docker run command for example. Be sure to remove the token if it is still present (it doesn't need to be after the first run).

**Comment by 7eventy7** [comment]
Seems like that might be the issue?
![image](https://github.com/user-attachments/assets/34c119c3-1a8c-4eb9-a299-8f40b1023197)

**Comment by PhasecoreX** [comment]
I don't know what that container manager is, but it is weird that it mentions `/config` instead of `/data`. I don't use `/config` in this image.

**Comment by JzJad** [comment]
Looks like unraid, and It does indeed look like thats missing the /data volume(Unless that tooltip is wrong/misleading. Would make since why you lost all config all of a sudden as the temporary volume likely got pruned. You would want to restore from a backup if possible, thats hopping the backup even had any real data.

**Comment by PhasecoreX** [comment]
But if the `/mnt/user/appdata/redbot` still has all the data in it, then simply mounting it to `/data` instead of `/config` should fix it.

**Comment by 7eventy7** [comment]
I found a thread on the unraid forums about this issue and the fix I was able to find was to just use a different image. There is another one avaliable on the CA store and apparently has a persistent data volume.

https://forums.unraid.net/topic/151206-support-community-applications-redbot/#comment-1471772

**Comment by PhasecoreX** [comment]
Cool, so then I assume your issue is resolved. If not, feel free to reopen, but keep in mind I don't have unraid and didn't make either of those images, so it might be better to reach out to whoever made those. Whoever made that first image, they should really consider mounting the `/data` instead of the `/config` directory if they want it to work at all lol.
